modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/Toggle-Beacon-Beams/issues"
license = "MIT"

[[mods]]
modId = "togglebeaconbeams"
version = "0.1.0"
displayName = "Toggle Beacon Beams"
authors = "CoolAid48"
credits = "MandaLin (Mod icon and sprites)"
description = '''
Adds a simple beacon beam toggle button to the beacon UI
'''
logoFile = "assets/tbb/icon.png"

[[mixins]]
config = "tbb.mixins.json"
